# Generated by Django 3.0.3 on 2020-04-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logins',
            fields=[
                ('faculty_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='registered',
            fields=[
                ('subject_name', models.CharField(max_length=200)),
                ('subject_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=200)),
                ('faculty_id', models.CharField(max_length=200)),
            ],
        ),
    ]
